import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './css/globals.scss'
import './css/helpers.scss'
import localFont from "next/font/local"

const inter = Inter({ subsets: ['latin'] })
const basementFont = localFont({
  src: '../../fonts/BasementFont.woff',
})

export const metadata: Metadata = {
  title: 'Basement challenge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html  data-scroll-container lang="en">
      <body   className={basementFont.className}>{children}</body>
    </html>
  )
}
